language: ruby

cache: bundler

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.1.7
  - gemfiles/Gemfile.rails-5.2.4.4
  - gemfiles/Gemfile.rails-6.0.3.3

before_install:
  - gem update bundler
