version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

references:
  set_env: &set_env
    run:
      name: Set up environment
      command: |
        echo "export BUNDLE_GEMFILE=$(pwd)/gemfiles/Gemfile.rails-$RAILS_VERSION" >> $BASH_ENV
  bundle: &bundle
    run:
      name: Install dependencies
      command: bundle install
  print_versions: &print_versions
    run:
      name: Print ruby and rails versions
      command: |
        ruby -v
        bundle exec rails -v
  test: &test
    run:
      name: Run test suite
      command: bundle exec rake

jobs:
  test:
    docker:
      - image: "cimg/ruby:<< parameters.ruby_version >>-browsers"
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - checkout
      - browser-tools/install-chrome
      - <<: *set_env
      - <<: *bundle
      - <<: *print_versions
      - <<: *test

workflows:
  default:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version: ["2.5", "2.6", "2.7"]
              rails_version: ["5.1.4", "6.1.4"]
