version: 2.1

references:
  set_env: &set_env
    run:
      name: Set up environment
      command: |
        echo "export BUNDLE_GEMFILE=$(pwd)/gemfiles/Gemfile.rails-$RAILS_VERSION" >> $BASH_ENV
  bundle: &bundle
    run:
      name: Install dependencies
      command: bundle install
  test: &test
    run:
      name: Run test suite
      command: bundle exec rake

jobs:
  test:
    docker:
      - image: "cimg/ruby:<< parameters.ruby_version >>"
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - checkout
      - <<: *set_env
      - <<: *bundle
      - <<: *test

workflows:
  default:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version: ["2.5", "2.6", "2.7"]
              rails_version: ["5.0.6", "5.1.4", "6.1.4"]
